# -*- coding: utf-8 -*-
"""Финал

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16xXUkwpLeyDQuu-dD1EgnLWXiLKc3boO
"""

import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats

"""Задание 1"""

df = pd.read_csv('HR.csv')
df

"""Задание 2"""

df.describe()

df.mode()

"""Задание 3"""

df_4_matrix = df[['satisfaction_level','last_evaluation','number_project','average_montly_hours','time_spend_company','Work_accident','left','promotion_last_5years']]
df

graph = plt.figure(figsize=(14, 12))
plt.matshow(df_4_matrix.corr(), fignum=graph.number)
plt.xticks(range(df_4_matrix.shape[1]), df_4_matrix.columns, fontsize=10, rotation=15)
plt.yticks(range(df_4_matrix.shape[1]), df_4_matrix.columns, fontsize=10)
gr = plt.colorbar()
gr.ax.tick_params(labelsize=10)

"""Две самые скоррелированные:
average_montly_hours & number_project

---


Две наименее скоррелированные:
left & satisfaction_level

Задание 4
"""

df.groupby('department')['department'].count()

"""Задание 5"""

df.groupby('salary')['salary'].count().plot(kind="bar")

"""Задание 6"""

Sal_rasp = df.groupby([df['department'],df['salary']])[['salary']].count()
Sal_rasp

"""Задание 7"""

high_sal = list(df.loc[df['salary'] == 'high']['average_montly_hours'])
low_sal = list(df.loc[df['salary'] == 'low']['average_montly_hours'])
plt.hist(high_sal, bins=100, density=True);
plt.hist(low_sal, bins=100, density=True);

first, second = stats.ttest_ind(high_sal, low_sal)
print(first, second)

"""Гипотеза не верна"""

df_uvol = df.loc[df['left'] == 1]
df_uvol

len(df_uvol.loc[df_uvol['promotion_last_5years'] == 1])/len(df_uvol)

df_uvol['satisfaction_level'].mean()

df_uvol['number_project'].mean()

df_ne_uvol = df.loc[df['left'] == 0]
df_ne_uvol

len(df_ne_uvol.loc[df_ne_uvol['promotion_last_5years'] == 1])/len(df_ne_uvol)

df_ne_uvol['satisfaction_level'].mean()

df_ne_uvol['number_project'].mean()